#!/usr/bin/env python
import re
import sys

# workaround for EASY-INSTALL-ENTRY-SCRIPT error "KeyError: 'config.option'"
from salt.scripts import salt_call

if __name__ == "__main__":
    sys.argv[0] = re.sub(r"(-script\.pyw?|\.exe)?$", "", sys.argv[0])
    sys.exit(salt_call())
